### PR TITLE
fix(rtnt): Packet payload not converting to/from Network <-> Host (`ntohX`/`htonX`)

### LINKED ISSUE #68: bug(lib>rtnt): Packet payload not converting to Network <-> Host (`ntohX`/`htonX`).
### Describe the bug

When sending or receiving a packet, the header is properly converted to/from network/host, but the payload isn't.

### How to Reproduce

Make two machines with different endianness communicate with each other with the `rtnt` library, and watch the packets payloads get messy (will inevitably have a butterfly effect on the program).

### Expected behavior

Payload misinterpretation, "weird" issues.

### Additional context

ty @nellousan for spotting the bug

### Pre-submission checklist

- [x] I have SET the appropriate label
- [x] I have SET the appropriate milestone
- [x] I have UNSET the issue tag

### PR DESCRIPTION
**Pull request by Shuvlyy**
# fix(rtnt): Packet payload not converting to/from Network <-> Host (`ntohX`/`htonX`)

## Issues closed
Closes #68 

## Summary
Fixed lack of endianness management in packet payloads.

## Changes
- Added a `rtnt::endian::swap()` function to reverse the bytes of a given type (`uin16_t`, `float`...) to convert it from/to network/host.
- Moved `ByteBuffer` alias declaration to `Constants.hpp` header file
- Removed `Header::toHost` function because `rtnt::endian::swap()` function is symmetrical
- Refactored `Header::toNetwork` function (renamed it to `Header::convertEndianness` and `htonX` functions aren't called anymore, `rtnt::endian::swap()` is used instead.
- Changed library version from `1.1.2` to `1.1.3` 
- Added complex packet test that test a lot of different supported types

## Screenshots/Video
Screenshot 2025-12-17 at 4 40 38 PM

[rtnt_(tests)_2025-12-17_18-05-12..log](https://github.com/user-attachments/files/24218549/rtnt_.tests._2025-12-17_18-05-12.log)

## Checklist
- [x] I have renamed the first header of the template
- [x] I have tested my modifications
- [x] I have done the relevant documentation
- [x] I have set the Reviewers & Assignees
- [x] I have set the correct `Labels`
- [x] I have set the `rtype` project
- [x] I have set `Status` / `Priority` / `Size` / `Start date` / `End date`
- [x] I have set the relevant `Milestone`

### CODE REVIEW

File: lib/rtnt/tests/tests/complex_packet.cpp [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+
+        .s8 = -120,
+        .s16 = -30000,
+        .s32 = -2000000000,
+        .s64 = -9000000000000000000,
+
+        .f = 3.14159f,
+        .d = 1.23456789012345,
+
+        .s = "aymeric caca boudin 🥇",
```
Comment (Shuvlyy) [inline lib/rtnt/tests/tests/complex_packet.cpp]: banger

**Review by PierreMarguerie — APPROVED** [review]
